name: CICD
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  validate-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: npm install -g npm@11.7.0
      - run: npm install
      - run: npm run format
      - run: |
          git diff --exit-code || {
            echo "Code formatting issues found. Please run 'npm run format' and commit the changes."
            exit 1
          }
      - run: npm run build
      - run: |
          git diff --exit-code dist || {
            echo "Build output has changed. Please run 'npm run build' and commit the changes."
            exit 1
          }

  test-top-level:
    needs: validate-dist
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Test get job workflow
        uses: jenseng/dynamic-uses@v1
        with:
          uses: jenseng/get-job-workflow/.github/actions/test@${{ github.sha }}
          with: |
            expected-repository: jenseng/get-job-workflow
            expected-path: .github/workflows/cicd.yml
            expected-ref: ${{ toJSON(github.ref) }}
            expected-sha: ${{ toJSON(github.workflow_sha) }}

  test-nested-local:
    needs: validate-dist
    uses: ./.github/workflows/test-nested.yml
    with:
      expected-repository: jenseng/get-job-workflow
      expected-path: .github/workflows/test-nested.yml
      expected-ref: ${{ github.ref }}
      expected-sha: ${{ github.workflow_sha }}

  test-nested-remote-via-sha:
    needs: validate-dist
    uses: jenseng/get-job-workflow/.github/workflows/test-nested.yml@8fe6cf3c7c02d021a440bd78c2de105ea78df6dc
    with:
      expected-repository: jenseng/get-job-workflow
      expected-path: .github/workflows/test-nested.yml
      expected-ref: ""
      expected-sha: 8fe6cf3c7c02d021a440bd78c2de105ea78df6dc

  test-nested-remote-via-ref:
    needs: validate-dist
    uses: jenseng/get-job-workflow/.github/workflows/test-nested.yml@nested-workflow-test-ref
    with:
      expected-repository: jenseng/get-job-workflow
      expected-path: .github/workflows/test-nested.yml
      expected-ref: refs/tags/nested-workflow-test-ref
      expected-sha: 8fe6cf3c7c02d021a440bd78c2de105ea78df6dc
